config/routes.rb
Rails.application.routes.draw do
  root :to => redirect('/main')
  resources 'sessions', only: [:create, :destroy]
  get '/main' => 'sessions#new'
  resources 'users', only: :create
  get '/dashboard/:id' => 'users#show'
  resources 'shoes', only: [:index, :create, :destroy]
  resources 'purchases', only: :create
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :shoe
  belongs_to :user

  validates :shoe, :user, presence: true
  validates :shoe, uniqueness: true

end

app/models/shoe.rb
class Shoe < ApplicationRecord
  belongs_to :user
  has_one :purchase
  has_one :buyer, through: :purchase, source: :user

  validates :name, :price, :user, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :shoes
  has_many :purchases
  has_many :shoes_purchased, through: :purchases, source: :shoe
  has_many :shoes_sold, through: :shoes, source: :purchase

  validates :first_name, :last_name, :email, presence: true
  validates :password, :password_confirmation, presence: true, if: :password_digest_changed?
  EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i
  validates :email, uniqueness: { case_sensitive: false }, format: { with: EMAIL_REGEX }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
  	User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
  
  def require_login
  	redirect_to main_path if session[:user_id] == nil
  end
  
  def require_correct_user
  	user = User.find(params[:id])
  	redirect_to "/dashboard/#{current_user['id']}" if current_user != user
  end

end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  
  before_action :require_login

  def create
  	p_params = purchase_params
  	p_params['shoe'] = Shoe.find(purchase_params['shoe_id'])
  	p_params.delete('shoe_id')
  	p_params['user'] = User.find(session[:user_id])
  	@purchase = Purchase.new( p_params )
  	if @purchase.save
  		redirect_to "/dashboard/#{session[:user_id]}"
  	else
  		redirect_to shoes_path
  	end
  end

  private
  	def purchase_params
  		params.require(:purchase).permit(:shoe_id)
  	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  	@user = User.new
  	@session = User.new
  end

  def create
	@session = User.find_by( email: session_params['email'] )
	if @session
		if !@session.authenticate( session_params['password'] )
			flash[:alert] = "Invalid Password"
  			redirect_to main_path
  		else
  			session[:user_id] = @session.id
  			redirect_to shoes_path
  		end
  	else
  		flash[:alert] = "Invalid Email"
  		redirect_to main_path
  	end
  end

  def destroy
  	session.clear
  	redirect_to main_path
  end

  private
  	def session_params
  		params.require(:user).permit(:email, :password)
  	end

end

app/controllers/shoes_controller.rb
class ShoesController < ApplicationController

  before_action :require_login

  def index
  	@bought = Purchase.pluck(:shoe_id)
  	@products = Shoe.where.not(id: @bought)
  	@purchase = Purchase.new
  end

  def create
  	s_params = shoe_params
  	s_params['user'] = current_user
  	@shoe = Shoe.new( s_params )
  	if @shoe.save
  		redirect_to "/dashboard/#{session[:user_id]}"
  	else
  		flash[:errors] = @shoe.errors.full_messages
  		redirect_to "/dashboard/#{session[:user_id]}"
  	end
  end

  def destroy
    Shoe.find( params[:id] ).destroy if current_user == Shoe.find( params[:id] ).user
    redirect_to "/dashboard/#{session[:user_id]}"
  end

  private
  	def shoe_params
  		params.require(:shoe).permit(:name, :price)
  	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_login, only: :show
  before_action :require_correct_user, only: :show

  def show
  	@shoe = Shoe.new
    @bought = Purchase.pluck(:shoe_id)
  	@listed = Shoe.where(user: current_user).where.not(id: @bought)
  	@sold = User.find( current_user.id ).shoes_sold
  	@purchased = User.find( current_user.id ).shoes_purchased
  end

  def create
  	@user = User.new( user_params )
  	if @user.save
  		session[:user_id] = @user.id
  		redirect_to shoes_path
  	else
  		flash[:errors] = @user.errors.full_messages
  		redirect_to main_path
  	end
  end

  private
  	def user_params
  		params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shoes_helper.rb
module ShoesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shoe Sale</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shoes/index.html.erb
<p>Hi <%= current_user.first_name %></p>
<a href="/dashboard/<%= current_user['id'] %>">User Dashboard</a>
<a href="<%= session_path('logout') %>" data-method="delete">Logout</a>
<h1>All Products</h1>
<table>
	<thead>
		<tr>
			<th>Product</th>
			<th>Seller</th>
			<th>Date Posted</th>
			<th>Amount</th>
			<th>Action</th>
		</tr>
	</thead>
	<tbody>
		<% @products.each do |p| %>
			<% if @bought.include?(p.id) %>
			<tr><td colspan="4">Bought</td></tr>
			<% else %>
			<tr>
				<td><%= p.name %></td>
				<td><%= p.user.first_name %> <%= p.user.last_name %></td>
				<td><%= p.created_at.strftime('%D') %></td>
				<td><%= number_to_currency(p.price) %></td>
				<td>
					<%= form_for @purchase do |f| %>
						<%= f.hidden_field :shoe_id, :value => p.id %>
						<%= f.submit :value => "Buy" %>
					<% end %>
				</td>
			</tr>
			<% end %>
		<% end %>
	</tbody>
</table>

app/views/users/show.html.erb
<p>Hi <%= current_user.first_name %></p>
<a href="<%= shoes_path %>">All Products</a>
<a href="<%= session_path %>" data-method="delete">Logout</a>

<div>
	<h2>Sell Product</h2>

	<% if flash[:errors] %>
		<% flash[:errors].each do |err| %>
			<p><%= err %></p>
		<% end %>
	<% end %>

	<%= form_for @shoe do |f| %>

		<%= f.label :name %>
		<%= f.text_field :name %>

		<%= f.label :price %>
		<%= f.number_field :price, :step => 0.01 %>

		<%= f.submit :value => "List for Sale" %>

	<% end %>
</div>
<div>
	<h2>Your Listed Products</h2>
	<table>
		<thead>
			<tr>
				<th>Product</th>
				<th>Date Posted</th>
				<th>Amount</th>
				<th>Action</th>
			</tr>
		</thead>
		<tbody>
			<% @listed.each do |s| %>
				<% unless @sold.include?(s) %>
				<tr>
					<td><%= s.name %></td>
					<td><%= s.created_at.strftime('%D') %></td>
					<td><%= number_to_currency(s.price) %></td>
					<td><a href="<%= shoe_path(s.id) %>" data-method="delete">Delete</a></td>
				</tr>
				<% end %>
			<% end %>
		</tbody>
	</table>
</div>
<div>
	<h2>Your Sold Products</h2>
	<table>
		<thead>
			<tr>
				<th>Product</th>
				<th>Date Bought</th>
				<th>Buyer</th>
				<th>Amount</th>
			</tr>
		</thead>
		<tbody>
			<% @sold.each do |s| %>
			<tr>
				<td><%= s.shoe.name %></td>
				<td><%= s.created_at.strftime('%D') %></td>
				<td><%= s.shoe.buyer.first_name %> <%= s.shoe.buyer.last_name %></td>
				<td><%= number_to_currency(s.shoe.price) %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
	<h3>Total: <%= number_to_currency(@sold.sum(:price)) %></h3>
</div>
<div>
	<h2>Your Purchased Products</h2>
	<table>
		<thead>
			<tr>
				<th>Product</th>
				<th>Date Bought</th>
				<th>Seller</th>
				<th>Amount</th>
			</tr>
		</thead>
		<tbody>
			<% @purchased.each do |s| %>
			<tr>
				<td><%= s.name %></td>
				<td><%= s.purchase.created_at.strftime('%D') %></td>
				<td><%= s.user.first_name %> <%= s.user.last_name %></td>
				<td><%= number_to_currency(s.price) %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
	<h3>Total: <%= number_to_currency(@purchased.sum(:price)) %></h3>
</div>